logfile: log/boss.log
daemon: true
applications:
  rails:
    period: 3600
    stakeholders:
      - john.doe@foo.bar
    whitelisted_authors:
      - john.doe@foo.bar
    whitelisted_authors_regex:
      .+@foo.bar
    deployment_task: deploy.example
    postpone_for: 3600
    deploy_after: 25200
    deploy_before: 61200
    repository: git@github.com:rails/rails.git
    branch: master
mail:
  smtp_server: smtp.gmail.com
  port: 587
  domain: your.host.name
  user_name: username
  password: password
  authentication: plain
  enable_starttls_auto: true
